package casa_licitatii;

import java.util.ArrayList;
import java.util.List;

import my_pair.MyTuple;

/**
 * An auction performed by the auction house;
 * It is characterized by an id,by the id of the product
 * which is being sold,by a number of participants and a number
 * of rounds(randomly generated by the auction house);
 * Moreover,the auction is performed in a separate thread,identified by
 * the field associatedThread.
 * Every round of an auction consists in a list of proposals.
 * A proposal consists in a tuple of 3 elements:the index of a broker,
 * the value of the bid and the max price the client of respective broker
 * is willing to give.
 * @author Saceleanu Andrei
 *
 */
public class Licitatie {
	private int id;
	private int nrParticipanti;
	private int idProdus;
	private int nrPasiMaxim;
	private List<MyTuple<Integer,Double, Double>> propuneriCurente;
	private Thread associatedThread;

	public Licitatie(int id, int nrParticipanti, int idProdus, int nrPasiMaxim) {
		this.id = id;
		this.nrParticipanti = nrParticipanti;
		this.idProdus = idProdus;
		this.nrPasiMaxim = nrPasiMaxim;
		propuneriCurente=new ArrayList<>();
	}
	
	public Thread getAssociatedThread() {
		return associatedThread;
	}
	
	public void setAssociatedThread(Thread associatedThread) {
		this.associatedThread = associatedThread;
	}
	
	public List<MyTuple<Integer, Double, Double>> getPropuneriCurente() {
		return propuneriCurente;
	}

	public void setPropuneriCurente(List<MyTuple<Integer, Double, Double>> propuneriCurente) {
		this.propuneriCurente = propuneriCurente;
	}
	
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getNrParticipanti() {
		return nrParticipanti;
	}

	public void setNrParticipanti(int nrParticipanti) {
		this.nrParticipanti = nrParticipanti;
	}

	public int getIdProdus() {
		return idProdus;
	}

	public void setIdProdus(int idProdus) {
		this.idProdus = idProdus;
	}

	public int getNrPasiMaxim() {
		return nrPasiMaxim;
	}

	public void setNrPasiMaxim(int nrPasiMaxim) {
		this.nrPasiMaxim = nrPasiMaxim;
	}
	
	
}
